apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-container
        image: yadavkapil23/rag-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              # You must create a secret named 'nvidia-secret' beforehand
              name: nvidia-secret
              key: NVIDIA_API_KEY
        - name: NVIDIA_MODEL
          value: "openai/gpt-oss-20b"